### ISSUE TITLE
Prevent conversion from the same unit to the same unit can sometimes still be possible

### ISSUE THREAD

**Issue by http-error-500** [http-error-500/molar-mass-calculator#11]
When you immediately select inputConversion = moles.
AND
When you immediately select outputConversion = grams.

Maybe initially say these two values are impossible and then make this variable so that it instantly changes when given another value.

**Comment by danielkievit** [comment]
When selecting outputConversion = grams --> you can't select inputConversion = moles, while this should be possible.

**Comment by danielkievit** [comment]
When selecting outputConversion = grams --> then select ouputConversion = moles --> it gives an error while this is not necessary. It thinks the value is still moles somehow.

**Comment by danielkievit** [comment]
Solved by creating the same order of options in the html list.

Moles grams litres
Moles grams litres
